version: '3'
services:
  java:
    image: divyagujjarlapudi/nitjava
    ports:
      - "8000:80"
    volumes:
      - "javavolume"

  devops:
    image: divyagujjarlapudi/nitdevops
    ports:
      - "8001:80"
    volumes:
      - "devopsvolume"

  datascience:
    image: divyagujjarlapudi/nitdatascience
    ports:
      - "8002:80"
    volumes:
      - "datasciencevolume"
